import Foundation
import SwiftUI

@MainActor
class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()

    @Published var currentLanguage: AppLanguage = .french {
        didSet {
            loadStrings()
        }
    }

    private var strings: [String: String] = [:]

    init() {
        loadStrings()
    }

    func setLanguage(_ language: AppLanguage) {
        currentLanguage = language
    }

    private func loadStrings() {
        strings = currentLanguage == .french ? frenchStrings : englishStrings
    }

    func localized(_ key: String) -> String {
        strings[key] ?? key
    }

    subscript(key: String) -> String {
        localized(key)
    }

    // MARK: - French Strings

    private let frenchStrings: [String: String] = [
        // General
        "app_name": "FitAI",
        "continue": "Continuer",
        "save": "Enregistrer",
        "cancel": "Annuler",
        "delete": "Supprimer",
        "edit": "Modifier",
        "done": "Terminé",
        "next": "Suivant",
        "back": "Retour",
        "close": "Fermer",
        "yes": "Oui",
        "no": "Non",
        "ok": "OK",
        "error": "Erreur",
        "success": "Succès",
        "loading": "Chargement...",

        // Tab Bar
        "tab_home": "Accueil",
        "tab_workouts": "Entraînements",
        "tab_meals": "Repas",
        "tab_assistant": "Assistant",
        "tab_tracking": "Suivi",
        "tab_settings": "Paramètres",

        // Onboarding
        "onboarding_welcome": "Bienvenue sur FitAI",
        "onboarding_subtitle": "Votre coach personnel pour la prise de masse",
        "onboarding_name": "Prénom (optionnel)",
        "onboarding_age": "Âge",
        "onboarding_weight": "Poids (kg)",
        "onboarding_height": "Taille (cm)",
        "onboarding_sex": "Sexe",
        "onboarding_equipment": "Équipement",
        "onboarding_sessions": "Séances par semaine",
        "onboarding_language": "Langue",
        "onboarding_create_profile": "Créer mon profil",
        "onboarding_disclaimer_title": "Avertissement Santé",
        "onboarding_disclaimer_text": "Cette application fournit des conseils généraux de fitness et ne remplace pas l'avis d'un professionnel de santé. Consultez un médecin avant de commencer tout programme d'exercice. En utilisant cette application, vous reconnaissez que vous êtes responsable de votre propre santé et forme physique.",
        "onboarding_accept_disclaimer": "J'accepte et je comprends",
        "onboarding_notifications": "Activer les notifications",
        "onboarding_notifications_desc": "Recevez des rappels pour vos séances d'entraînement",
        "onboarding_enter_age": "Entrez votre âge",
        "onboarding_enter_weight": "Entrez votre poids en kg",
        "onboarding_enter_height": "Entrez votre taille en cm",
        "onboarding_regime_title": "Régime alimentaire",
        "onboarding_regime_subtitle": "Quel type d'alimentation suivez-vous ?",
        "onboarding_allergies_title": "Allergies",
        "onboarding_allergies_subtitle": "Sélectionnez vos allergies alimentaires",
        "onboarding_dislikes_title": "Aliments à éviter",
        "onboarding_dislikes_subtitle": "Y a-t-il des aliments que vous n'aimez pas ?",

        // Sex
        "sex_male": "Homme",
        "sex_female": "Femme",
        "sex_other": "Autre",

        // Fitness Goals
        "onboarding_goal_title": "Quel est votre objectif ?",
        "onboarding_goal_subtitle": "Nous adapterons vos repas et entraînements en conséquence",
        "goal_weight_loss": "Perte de poids",
        "goal_weight_loss_desc": "Brûler les graisses tout en préservant la masse musculaire",
        "goal_muscle_gain": "Prise de masse",
        "goal_muscle_gain_desc": "Développer la masse musculaire avec un surplus calorique",
        "goal_maintenance": "Maintien",
        "goal_maintenance_desc": "Garder votre physique actuel et rester en forme",
        "goal_recomposition": "Recomposition",
        "goal_recomposition_desc": "Perdre du gras et gagner du muscle simultanément",

        // Equipment
        "equipment_dumbbells": "Haltères",
        "equipment_none": "Sans matériel",

        // Dietary Regimes
        "diet_standard": "Standard",
        "diet_vegetarian": "Végétarien",
        "diet_vegan": "Végan",
        "diet_pescatarian": "Pescétarien",
        "diet_keto": "Keto",
        "diet_paleo": "Paléo",
        "diet_mediterranean": "Méditerranéen",

        // Food Allergies
        "allergy_gluten": "Gluten",
        "allergy_lactose": "Lactose",
        "allergy_nuts": "Fruits à coque",
        "allergy_peanuts": "Arachides",
        "allergy_shellfish": "Crustacés",
        "allergy_eggs": "Œufs",
        "allergy_soy": "Soja",
        "allergy_fish": "Poisson",

        // Food Dislikes
        "dislike_red_meat": "Viande rouge",
        "dislike_pork": "Porc",
        "dislike_chicken": "Poulet",
        "dislike_fish": "Poisson",
        "dislike_seafood": "Fruits de mer",
        "dislike_eggs": "Œufs",
        "dislike_dairy": "Produits laitiers",
        "dislike_spicy": "Épicé",
        "dislike_mushrooms": "Champignons",
        "dislike_onions": "Oignons",

        // Dietary Settings
        "settings_dietary": "Préférences alimentaires",
        "settings_dietary_regime": "Régime alimentaire",
        "settings_allergies": "Allergies",
        "settings_dislikes": "Aliments à éviter",
        "settings_no_allergies": "Aucune allergie",
        "settings_no_dislikes": "Aucun aliment à éviter",

        // Difficulty
        "difficulty_beginner": "Débutant",
        "difficulty_intermediate": "Intermédiaire",
        "difficulty_advanced": "Avancé",

        // Muscle Groups
        "muscle_chest": "Poitrine",
        "muscle_back": "Dos",
        "muscle_shoulders": "Épaules",
        "muscle_biceps": "Biceps",
        "muscle_triceps": "Triceps",
        "muscle_legs": "Jambes",
        "muscle_core": "Abdominaux",
        "muscle_glutes": "Fessiers",
        "muscle_full_body": "Corps entier",

        // Home
        "home_today_workout": "Séance du jour",
        "home_no_workout": "Pas de séance aujourd'hui",
        "home_rest_day": "Jour de repos",
        "home_workout_done": "Séance terminée !",
        "home_workout_done_subtitle": "Bravo ! Vous avez terminé votre entraînement du jour.",
        "home_start_workout": "Démarrer la séance",
        "home_view_program": "Voir le programme",
        "home_view_meals": "Voir le menu",
        "home_generate_menu": "Générer le menu du jour",
        "home_duration": "Durée estimée",
        "home_minutes": "min",
        "home_exercises": "exercices",
        "home_week": "Semaine",
        "home_day": "Jour",
        "home_completed": "Terminée",
        "home_stats_title": "Vos progrès",
        "home_total_workouts": "Séances totales",
        "home_this_week": "Cette semaine",
        "home_weight_change": "Évolution poids",

        // Workouts
        "workouts_title": "Programme",
        "workouts_week": "Semaine",
        "workouts_generate": "Générer la semaine",
        "workouts_regenerate": "Regénérer",
        "workouts_empty": "Aucun programme généré",
        "workouts_empty_desc": "Générez votre premier programme d'entraînement",
        "workouts_delete": "Supprimer cette semaine",
        "workouts_delete_confirm": "Voulez-vous supprimer le programme de cette semaine ?",
        "workouts_current": "Actuelle",
        "workouts_completed": "terminées",
        "workouts_not_generated": "Non générée",
        "workouts_sessions": "Séances",
        "workouts_exercises": "Exercices",
        "workouts_difficulty": "Difficulté",

        // Workout Detail
        "workout_sets": "séries",
        "workout_reps": "reps",
        "workout_rest": "Repos",
        "workout_seconds": "sec",
        "workout_tempo": "Tempo",
        "workout_log_session": "Enregistrer la séance",
        "workout_complete": "Terminer",
        "workout_notes": "Notes",
        "workout_add_notes": "Ajouter des notes...",
        "workout_weight_used": "Poids utilisé (kg)",
        "workout_reps_done": "Répétitions effectuées",
        "workout_session_saved": "Séance enregistrée !",
        "workout_rate": "Noter la séance",
        "workout_last_weight": "Dernier poids",
        "workout_difficulty_question": "Comment était cette séance ?",
        "workout_difficulty_desc": "Votre feedback nous aide à ajuster les poids pour la prochaine fois",
        "difficulty_too_easy": "Trop facile",
        "difficulty_just_right": "Parfait",
        "difficulty_too_hard": "Trop dur",

        // Exercise Detail
        "exercise_watch_video": "Voir la vidéo",
        "exercise_no_image": "Pas d'image disponible",
        "exercise_muscles": "Muscles ciblés",
        "exercise_instructions": "Instructions",
        "exercise_tips": "Conseils",
        "exercise_tip_form": "Gardez une bonne posture tout au long du mouvement",
        "exercise_tip_breathing": "Expirez à l'effort, inspirez au retour",
        "exercise_tip_control": "Contrôlez le mouvement, évitez les à-coups",
        "exercise_how_to": "Comment faire ?",
        "exercise_secondary_muscles": "Muscles secondaires",
        "exercise_description": "Description",

        // Active Workout
        "active_workout_title": "Séance en cours",
        "active_workout_set": "Série",
        "active_workout_of": "sur",
        "active_workout_next": "Suivant",
        "active_workout_previous": "Précédent",
        "active_workout_finish": "Terminer la séance",
        "active_workout_rest_timer": "Temps de repos",
        "active_workout_skip_rest": "Passer",

        // Meals
        "meals_title": "Plan repas",
        "meals_today": "Aujourd'hui",
        "meals_breakfast": "Petit-déjeuner",
        "meals_lunch": "Déjeuner",
        "meals_dinner": "Dîner",
        "meals_snacks": "Collations",
        "meals_generate": "Générer le menu",
        "meals_regenerate": "Regénérer",
        "meals_kcal": "kcal",
        "meals_protein": "Protéines",
        "meals_carbs": "Glucides",
        "meals_fats": "Lipides",
        "meals_total": "Total journalier",
        "meals_empty": "Aucun plan repas",
        "meals_empty_desc": "Générez votre plan repas du jour",
        "meals_grams": "g",
        "meals_ingredients": "Ingrédients",
        "meals_instructions": "Préparation",
        "meals_delete": "Supprimer ce menu",
        "meals_delete_confirm": "Voulez-vous supprimer le menu de ce jour ?",

        // Water
        "water_title": "Hydratation",
        "water_glasses": "verres",
        "water_goal": "Objectif",
        "water_add": "Ajouter un verre",

        // Assistant
        "assistant_title": "Assistant IA",
        "assistant_placeholder": "Posez votre question...",
        "assistant_send": "Envoyer",
        "assistant_welcome": "Bonjour ! Je suis votre assistant fitness. Comment puis-je vous aider ?",
        "assistant_quick_actions": "Actions rapides",
        "assistant_generate_week": "Générer semaine 1",
        "assistant_enable_reminders": "Activer rappels",
        "assistant_explain_macros": "Expliquer les macros",
        "assistant_tips": "Conseils du jour",

        // Tracking
        "tracking_title": "Suivi",
        "tracking_weight": "Poids",
        "tracking_sessions": "Séances",
        "tracking_add_weight": "Ajouter poids",
        "tracking_current_weight": "Poids actuel",
        "tracking_start_weight": "Poids initial",
        "tracking_progress": "Progression",
        "tracking_no_data": "Pas encore de données",
        "tracking_no_data_desc": "Commencez à enregistrer votre poids",
        "tracking_no_sessions_desc": "Terminez votre première séance pour voir votre historique",
        "tracking_history": "Historique",
        "tracking_export": "Exporter CSV",
        "tracking_kg": "kg",
        "tracking_tap_to_edit": "Appuyez pour saisir manuellement",
        "tracking_gained": "pris",
        "tracking_lost": "perdu",

        // Settings
        "settings_title": "Paramètres",
        "settings_profile": "Profil",
        "settings_notifications": "Notifications",
        "settings_notifications_enabled": "Activer les notifications",
        "settings_reminder": "Rappel avant séance",
        "settings_minutes_before": "minutes avant",
        "settings_language": "Langue",
        "settings_about": "À propos",
        "settings_disclaimer": "Avertissement santé",
        "settings_reset": "Réinitialiser l'application",
        "settings_reset_confirm": "Êtes-vous sûr de vouloir tout réinitialiser ? Cette action est irréversible.",
        "settings_version": "Version",
        "settings_export_data": "Exporter mes données",

        // Exercise Names
        "ex_push_ups": "Pompes",
        "ex_diamond_push_ups": "Pompes diamant",
        "ex_wide_push_ups": "Pompes écartées",
        "ex_decline_push_ups": "Pompes déclinées",
        "ex_pike_push_ups": "Pompes piquées",
        "ex_dumbbell_bench_press": "Développé couché haltères",
        "ex_dumbbell_flyes": "Écarté haltères",
        "ex_incline_dumbbell_press": "Développé incliné haltères",
        "ex_dumbbell_pullover": "Pull-over haltères",
        "ex_dumbbell_rows": "Rowing haltères",
        "ex_single_arm_row": "Rowing un bras",
        "ex_renegade_rows": "Rowing renegade",
        "ex_dumbbell_deadlift": "Soulevé de terre haltères",
        "ex_dumbbell_shoulder_press": "Développé épaules haltères",
        "ex_lateral_raises": "Élévations latérales",
        "ex_front_raises": "Élévations frontales",
        "ex_rear_delt_flyes": "Oiseau arrière épaules",
        "ex_dumbbell_shrugs": "Shrugs haltères",
        "ex_bicep_curls": "Curl biceps",
        "ex_hammer_curls": "Curl marteau",
        "ex_concentration_curls": "Curl concentration",
        "ex_tricep_kickbacks": "Kickback triceps",
        "ex_tricep_extensions": "Extension triceps",
        "ex_close_grip_push_ups": "Pompes serrées",
        "ex_goblet_squats": "Goblet squats",
        "ex_lunges": "Fentes",
        "ex_bulgarian_split_squats": "Fentes bulgares",
        "ex_dumbbell_rdl": "RDL haltères",
        "ex_calf_raises": "Mollets debout",
        "ex_glute_bridges": "Pont fessier",
        "ex_hip_thrusts": "Hip thrust",
        "ex_step_ups": "Step-ups",
        "ex_wall_sit": "Chaise murale",
        "ex_squats": "Squats",
        "ex_jump_squats": "Squats sautés",
        "ex_plank": "Planche",
        "ex_side_plank": "Planche latérale",
        "ex_mountain_climbers": "Mountain climbers",
        "ex_leg_raises": "Relevés de jambes",
        "ex_russian_twists": "Russian twists",
        "ex_crunches": "Crunchs",
        "ex_bicycle_crunches": "Crunchs vélo",
        "ex_dead_bug": "Dead bug",
        "ex_superman": "Superman",
        "ex_burpees": "Burpees",
        "ex_jumping_jacks": "Jumping jacks",
        "ex_high_knees": "Genoux hauts",

        // Workout Types
        "workout_full_body": "Full Body",
        "workout_upper_body": "Haut du corps",
        "workout_lower_body": "Bas du corps",
        "workout_push": "Push",
        "workout_pull": "Pull",
        "workout_legs": "Jambes",
        "workout_arms": "Bras",
        "workout_core": "Abdos",
        "workout_challenge": "Challenge",

        // New Exercises
        "ex_arnold_press": "Arnold Press",
        "ex_incline_curls": "Curls inclinés",
        "ex_skull_crushers": "Skull Crushers",
        "ex_sumo_squats": "Squats sumo",
        "ex_weighted_crunches": "Crunchs lestés",
        "ex_archer_push_ups": "Pompes archer",
        "ex_handstand_hold": "Équilibre sur les mains",
        "ex_bench_dips": "Dips sur banc",
        "ex_pistol_squats": "Pistol squats",
        "ex_jumping_lunges": "Fentes sautées",
        "ex_single_leg_glute_bridge": "Pont fessier unipodal",
        "ex_donkey_kicks": "Donkey kicks",
        "ex_hollow_hold": "Hollow hold",
        "ex_v_ups": "V-ups",
        "ex_reverse_snow_angels": "Snow angels inversés",
        "ex_star_jumps": "Star jumps",
        "ex_dumbbell_complex": "Complexe haltères",
        "ex_complex_note": "Curl + Press + Squat enchaînés",

        // Meal Names
        "meal_oatmeal_banana": "Flocons d'avoine banane",
        "meal_eggs_toast": "Œufs et tartines",
        "meal_protein_smoothie": "Smoothie protéiné",
        "meal_greek_yogurt": "Yaourt grec et fruits",
        "meal_chicken_rice": "Poulet riz légumes",
        "meal_pasta_beef": "Pâtes bœuf haché",
        "meal_salmon_quinoa": "Saumon quinoa",
        "meal_tuna_salad": "Salade de thon",
        "meal_steak_potatoes": "Steak pommes de terre",
        "meal_turkey_wrap": "Wrap dinde",
        "meal_fish_vegetables": "Poisson légumes",
        "meal_beef_stir_fry": "Bœuf sauté légumes",
        "meal_nuts_fruit": "Noix et fruits",
        "meal_protein_bar": "Barre protéinée",
        "meal_cottage_cheese": "Fromage blanc",

        // Days
        "day_monday": "Lundi",
        "day_tuesday": "Mardi",
        "day_wednesday": "Mercredi",
        "day_thursday": "Jeudi",
        "day_friday": "Vendredi",
        "day_saturday": "Samedi",
        "day_sunday": "Dimanche",

        // Errors
        "error_generation": "Erreur lors de la génération",
        "error_save": "Erreur lors de la sauvegarde",
        "error_load": "Erreur lors du chargement",

        // Authentication
        "auth_title": "Créer un compte",
        "auth_subtitle": "Sauvegardez vos données et synchronisez entre appareils",
        "auth_skip": "Continuer sans compte",
        "auth_signup": "S'inscrire",
        "auth_signin": "Se connecter",
        "auth_email": "Email",
        "auth_password": "Mot de passe",
        "auth_google": "Continuer avec Google",
        "auth_or": "ou",
        "auth_sign_out": "Se déconnecter",
        "auth_sign_out_confirm": "Voulez-vous vraiment vous déconnecter ? Vous devrez vous reconnecter pour accéder à vos données.",
        "auth_delete_account": "Supprimer le compte",
        "auth_delete_confirm": "Êtes-vous sûr de vouloir supprimer votre compte ? Toutes vos données seront perdues.",
        "auth_anonymous": "Compte invité",
        "auth_logged_in_as": "Connecté",
        "auth_not_logged_in": "Non connecté",
        "settings_account": "Compte",
        "settings_appearance": "Apparence",
        "settings_theme": "Thème",
        "settings_accent_color": "Couleur d'accent",
        "settings_danger_zone": "Zone danger",

        // Theme modes
        "theme_mode_system": "Système",
        "theme_mode_light": "Clair",
        "theme_mode_dark": "Sombre",

        // Accent colors
        "accent_color_teal": "Turquoise",
        "accent_color_coral": "Corail",
        "accent_color_purple": "Violet",
        "accent_color_blue": "Bleu",
        "accent_color_green": "Vert",
        "accent_color_orange": "Orange",
        "accent_color_pink": "Rose",

        // Notifications
        "settings_workout_time": "Heure d'entraînement",
        "notification_workout_time": "C'est l'heure de ton entraînement ! 💪",
        "notification_new_week": "Prépare ta semaine ! Génère ton programme d'entraînement pour la semaine à venir 📅",
        "notification_weekly_summary": "Ta semaine est terminée ! Découvre ton récap et prépare la suivante 📊",

        // Weekly Summary
        "summary_title": "Récap de la semaine",
        "summary_completed": "complété",
        "summary_sessions": "Séances",
        "summary_training_time": "Temps total",
        "summary_streak": "Série",
        "summary_days": "jours",
        "summary_avg_rating": "Note moyenne",
        "summary_weight_progress": "Évolution du poids",
        "summary_start": "Début",
        "summary_end": "Fin",
        "summary_best_exercises": "Meilleures progressions",
        "summary_nutrition": "Nutrition moyenne",
        "summary_recommendations": "Recommandations IA",
        "summary_no_recommendations": "Complétez quelques séances pour obtenir des recommandations personnalisées.",
        "summary_generate_next_week": "Générer la semaine suivante",
        "summary_banner_title": "Récap hebdomadaire disponible",
        "summary_banner_subtitle": "Voir votre bilan et préparer la semaine suivante",

        // Loading Overlays
        "meals_generating_title": "Préparation de vos repas",
        "meals_generating_subtitle": "L'IA crée un menu personnalisé selon vos objectifs",
        "workouts_generating_title": "Création de votre programme",
        "workouts_generating_subtitle": "L'IA optimise vos entraînements pour la semaine",

        // Premium / Subscription
        "premium_title": "FitAI Premium",
        "premium_unlock": "Débloquez tout le potentiel de l'IA",
        "premium_subtitle": "Génération illimitée de programmes et repas personnalisés",
        "premium_feature_ai": "IA Illimitée",
        "premium_feature_ai_desc": "Génération sans limite de programmes et repas",
        "premium_feature_meals": "Repas Personnalisés",
        "premium_feature_meals_desc": "Menus quotidiens adaptés à vos objectifs",
        "premium_feature_workouts": "Programmes Adaptatifs",
        "premium_feature_workouts_desc": "Entraînements qui évoluent avec vous",
        "premium_feature_summary": "Résumé Hebdo IA",
        "premium_feature_summary_desc": "Recommandations personnalisées chaque semaine",
        "premium_feature_regenerate": "Regénération Illimitée",
        "premium_feature_regenerate_desc": "Changez de programme quand vous voulez",
        "premium_monthly": "Mensuel",
        "premium_monthly_desc": "Facturation mensuelle, annulez à tout moment",
        "premium_yearly": "Annuel",
        "premium_yearly_desc": "Meilleure offre, économisez plus de 30%",
        "premium_month": "mois",
        "premium_subscribe": "S'abonner",
        "premium_restore": "Restaurer les achats",
        "premium_legal": "L'abonnement se renouvelle automatiquement. Annulez à tout moment dans les paramètres de l'App Store.",
        "premium_terms": "Conditions d'utilisation",
        "premium_privacy": "Politique de confidentialité",
        "premium_loading_error": "Impossible de charger les abonnements",
        "premium_retry": "Réessayer",
        "premium_remaining": "générations restantes ce mois",
        "premium_limit_reached": "Limite atteinte ce mois",
        "premium_upgrade": "Passer Premium",
        "premium_badge": "Premium",
        "premium_free_trial": "7 jours gratuits",
        "settings_subscription": "Abonnement",
        "settings_subscription_status": "Statut",
        "settings_subscription_free": "Gratuit",
        "settings_subscription_premium": "Premium",
        "settings_manage_subscription": "Gérer l'abonnement",
        "settings_premium_active": "Abonnement actif",
        "settings_free_plan": "Plan Gratuit",
        "settings_free_limits": "Générations IA limitées",
        "settings_workouts_remaining": "Programmes restants",
        "settings_meals_remaining": "Menus restants",
    ]

    // MARK: - English Strings

    private let englishStrings: [String: String] = [
        // General
        "app_name": "FitAI",
        "continue": "Continue",
        "save": "Save",
        "cancel": "Cancel",
        "delete": "Delete",
        "edit": "Edit",
        "done": "Done",
        "next": "Next",
        "back": "Back",
        "close": "Close",
        "yes": "Yes",
        "no": "No",
        "ok": "OK",
        "error": "Error",
        "success": "Success",
        "loading": "Loading...",

        // Tab Bar
        "tab_home": "Home",
        "tab_workouts": "Workouts",
        "tab_meals": "Meals",
        "tab_assistant": "Assistant",
        "tab_tracking": "Tracking",
        "tab_settings": "Settings",

        // Onboarding
        "onboarding_welcome": "Welcome to FitAI",
        "onboarding_subtitle": "Your personal coach for muscle building",
        "onboarding_name": "First name (optional)",
        "onboarding_age": "Age",
        "onboarding_weight": "Weight (kg)",
        "onboarding_height": "Height (cm)",
        "onboarding_sex": "Sex",
        "onboarding_equipment": "Equipment",
        "onboarding_sessions": "Sessions per week",
        "onboarding_language": "Language",
        "onboarding_create_profile": "Create my profile",
        "onboarding_disclaimer_title": "Health Disclaimer",
        "onboarding_disclaimer_text": "This app provides general fitness advice and does not replace professional medical advice. Consult a doctor before starting any exercise program. By using this app, you acknowledge that you are responsible for your own health and fitness.",
        "onboarding_accept_disclaimer": "I accept and understand",
        "onboarding_notifications": "Enable notifications",
        "onboarding_notifications_desc": "Get reminders for your workout sessions",
        "onboarding_enter_age": "Enter your age",
        "onboarding_enter_weight": "Enter your weight in kg",
        "onboarding_enter_height": "Enter your height in cm",
        "onboarding_regime_title": "Dietary Regime",
        "onboarding_regime_subtitle": "What type of diet do you follow?",
        "onboarding_allergies_title": "Allergies",
        "onboarding_allergies_subtitle": "Select your food allergies",
        "onboarding_dislikes_title": "Foods to Avoid",
        "onboarding_dislikes_subtitle": "Are there foods you don't like?",

        // Sex
        "sex_male": "Male",
        "sex_female": "Female",
        "sex_other": "Other",

        // Fitness Goals
        "onboarding_goal_title": "What's your goal?",
        "onboarding_goal_subtitle": "We'll adapt your meals and workouts accordingly",
        "goal_weight_loss": "Weight Loss",
        "goal_weight_loss_desc": "Burn fat while preserving muscle mass",
        "goal_muscle_gain": "Muscle Gain",
        "goal_muscle_gain_desc": "Build muscle mass with a caloric surplus",
        "goal_maintenance": "Maintenance",
        "goal_maintenance_desc": "Keep your current physique and stay fit",
        "goal_recomposition": "Recomposition",
        "goal_recomposition_desc": "Lose fat and gain muscle simultaneously",

        // Equipment
        "equipment_dumbbells": "Dumbbells",
        "equipment_none": "No equipment",

        // Dietary Regimes
        "diet_standard": "Standard",
        "diet_vegetarian": "Vegetarian",
        "diet_vegan": "Vegan",
        "diet_pescatarian": "Pescatarian",
        "diet_keto": "Keto",
        "diet_paleo": "Paleo",
        "diet_mediterranean": "Mediterranean",

        // Food Allergies
        "allergy_gluten": "Gluten",
        "allergy_lactose": "Lactose",
        "allergy_nuts": "Tree nuts",
        "allergy_peanuts": "Peanuts",
        "allergy_shellfish": "Shellfish",
        "allergy_eggs": "Eggs",
        "allergy_soy": "Soy",
        "allergy_fish": "Fish",

        // Food Dislikes
        "dislike_red_meat": "Red meat",
        "dislike_pork": "Pork",
        "dislike_chicken": "Chicken",
        "dislike_fish": "Fish",
        "dislike_seafood": "Seafood",
        "dislike_eggs": "Eggs",
        "dislike_dairy": "Dairy",
        "dislike_spicy": "Spicy food",
        "dislike_mushrooms": "Mushrooms",
        "dislike_onions": "Onions",

        // Dietary Settings
        "settings_dietary": "Dietary preferences",
        "settings_dietary_regime": "Diet type",
        "settings_allergies": "Allergies",
        "settings_dislikes": "Foods to avoid",
        "settings_no_allergies": "No allergies",
        "settings_no_dislikes": "No foods to avoid",

        // Difficulty
        "difficulty_beginner": "Beginner",
        "difficulty_intermediate": "Intermediate",
        "difficulty_advanced": "Advanced",

        // Muscle Groups
        "muscle_chest": "Chest",
        "muscle_back": "Back",
        "muscle_shoulders": "Shoulders",
        "muscle_biceps": "Biceps",
        "muscle_triceps": "Triceps",
        "muscle_legs": "Legs",
        "muscle_core": "Core",
        "muscle_glutes": "Glutes",
        "muscle_full_body": "Full Body",

        // Home
        "home_today_workout": "Today's Workout",
        "home_no_workout": "No workout today",
        "home_rest_day": "Rest day",
        "home_workout_done": "Workout done!",
        "home_workout_done_subtitle": "Great job! You've completed today's workout.",
        "home_start_workout": "Start Workout",
        "home_view_program": "View Program",
        "home_view_meals": "View Menu",
        "home_generate_menu": "Generate today's menu",
        "home_duration": "Estimated duration",
        "home_minutes": "min",
        "home_exercises": "exercises",
        "home_week": "Week",
        "home_day": "Day",
        "home_completed": "Completed",
        "home_stats_title": "Your Progress",
        "home_total_workouts": "Total workouts",
        "home_this_week": "This week",
        "home_weight_change": "Weight change",

        // Workouts
        "workouts_title": "Program",
        "workouts_week": "Week",
        "workouts_generate": "Generate week",
        "workouts_regenerate": "Regenerate",
        "workouts_empty": "No program generated",
        "workouts_empty_desc": "Generate your first workout program",
        "workouts_delete": "Delete this week",
        "workouts_delete_confirm": "Do you want to delete this week's program?",
        "workouts_current": "Current",
        "workouts_completed": "completed",
        "workouts_not_generated": "Not generated",
        "workouts_sessions": "Sessions",
        "workouts_exercises": "Exercises",
        "workouts_difficulty": "Difficulty",

        // Workout Detail
        "workout_sets": "sets",
        "workout_reps": "reps",
        "workout_rest": "Rest",
        "workout_seconds": "sec",
        "workout_tempo": "Tempo",
        "workout_log_session": "Log Session",
        "workout_complete": "Complete",
        "workout_notes": "Notes",
        "workout_add_notes": "Add notes...",
        "workout_weight_used": "Weight used (kg)",
        "workout_reps_done": "Reps completed",
        "workout_session_saved": "Session saved!",
        "workout_rate": "Rate session",
        "workout_last_weight": "Last weight",
        "workout_difficulty_question": "How was this session?",
        "workout_difficulty_desc": "Your feedback helps us adjust weights for next time",
        "difficulty_too_easy": "Too easy",
        "difficulty_just_right": "Just right",
        "difficulty_too_hard": "Too hard",

        // Exercise Detail
        "exercise_watch_video": "Watch Video",
        "exercise_no_image": "No image available",
        "exercise_muscles": "Target Muscles",
        "exercise_instructions": "Instructions",
        "exercise_tips": "Tips",
        "exercise_tip_form": "Maintain proper form throughout the movement",
        "exercise_tip_breathing": "Exhale on exertion, inhale on return",
        "exercise_tip_control": "Control the movement, avoid jerky motions",
        "exercise_how_to": "How to do it?",
        "exercise_secondary_muscles": "Secondary muscles",
        "exercise_description": "Description",

        // Active Workout
        "active_workout_title": "Active Workout",
        "active_workout_set": "Set",
        "active_workout_of": "of",
        "active_workout_next": "Next",
        "active_workout_previous": "Previous",
        "active_workout_finish": "Finish Workout",
        "active_workout_rest_timer": "Rest Timer",
        "active_workout_skip_rest": "Skip",

        // Meals
        "meals_title": "Meal Plan",
        "meals_today": "Today",
        "meals_breakfast": "Breakfast",
        "meals_lunch": "Lunch",
        "meals_dinner": "Dinner",
        "meals_snacks": "Snacks",
        "meals_generate": "Generate Menu",
        "meals_regenerate": "Regenerate",
        "meals_kcal": "kcal",
        "meals_protein": "Protein",
        "meals_carbs": "Carbs",
        "meals_fats": "Fats",
        "meals_total": "Daily Total",
        "meals_empty": "No meal plan",
        "meals_empty_desc": "Generate your daily meal plan",
        "meals_grams": "g",
        "meals_ingredients": "Ingredients",
        "meals_instructions": "Instructions",
        "meals_delete": "Delete this menu",
        "meals_delete_confirm": "Do you want to delete this day's menu?",

        // Water
        "water_title": "Hydration",
        "water_glasses": "glasses",
        "water_goal": "Goal",
        "water_add": "Add a glass",

        // Assistant
        "assistant_title": "AI Assistant",
        "assistant_placeholder": "Ask your question...",
        "assistant_send": "Send",
        "assistant_welcome": "Hello! I'm your fitness assistant. How can I help you?",
        "assistant_quick_actions": "Quick Actions",
        "assistant_generate_week": "Generate Week 1",
        "assistant_enable_reminders": "Enable Reminders",
        "assistant_explain_macros": "Explain Macros",
        "assistant_tips": "Today's Tips",

        // Tracking
        "tracking_title": "Tracking",
        "tracking_weight": "Weight",
        "tracking_sessions": "Sessions",
        "tracking_add_weight": "Add Weight",
        "tracking_current_weight": "Current weight",
        "tracking_start_weight": "Starting weight",
        "tracking_progress": "Progress",
        "tracking_no_data": "No data yet",
        "tracking_no_data_desc": "Start logging your weight",
        "tracking_no_sessions_desc": "Complete your first workout to see your history",
        "tracking_history": "History",
        "tracking_export": "Export CSV",
        "tracking_kg": "kg",
        "tracking_tap_to_edit": "Tap to enter manually",
        "tracking_gained": "gained",
        "tracking_lost": "lost",

        // Settings
        "settings_title": "Settings",
        "settings_profile": "Profile",
        "settings_notifications": "Notifications",
        "settings_notifications_enabled": "Enable notifications",
        "settings_reminder": "Reminder before workout",
        "settings_minutes_before": "minutes before",
        "settings_language": "Language",
        "settings_about": "About",
        "settings_disclaimer": "Health disclaimer",
        "settings_reset": "Reset app",
        "settings_reset_confirm": "Are you sure you want to reset everything? This action cannot be undone.",
        "settings_version": "Version",
        "settings_export_data": "Export my data",

        // Exercise Names
        "ex_push_ups": "Push-ups",
        "ex_diamond_push_ups": "Diamond Push-ups",
        "ex_wide_push_ups": "Wide Push-ups",
        "ex_decline_push_ups": "Decline Push-ups",
        "ex_pike_push_ups": "Pike Push-ups",
        "ex_dumbbell_bench_press": "Dumbbell Bench Press",
        "ex_dumbbell_flyes": "Dumbbell Flyes",
        "ex_incline_dumbbell_press": "Incline Dumbbell Press",
        "ex_dumbbell_pullover": "Dumbbell Pullover",
        "ex_dumbbell_rows": "Dumbbell Rows",
        "ex_single_arm_row": "Single Arm Row",
        "ex_renegade_rows": "Renegade Rows",
        "ex_dumbbell_deadlift": "Dumbbell Deadlift",
        "ex_dumbbell_shoulder_press": "Dumbbell Shoulder Press",
        "ex_lateral_raises": "Lateral Raises",
        "ex_front_raises": "Front Raises",
        "ex_rear_delt_flyes": "Rear Delt Flyes",
        "ex_dumbbell_shrugs": "Dumbbell Shrugs",
        "ex_bicep_curls": "Bicep Curls",
        "ex_hammer_curls": "Hammer Curls",
        "ex_concentration_curls": "Concentration Curls",
        "ex_tricep_kickbacks": "Tricep Kickbacks",
        "ex_tricep_extensions": "Tricep Extensions",
        "ex_close_grip_push_ups": "Close Grip Push-ups",
        "ex_goblet_squats": "Goblet Squats",
        "ex_lunges": "Lunges",
        "ex_bulgarian_split_squats": "Bulgarian Split Squats",
        "ex_dumbbell_rdl": "Dumbbell RDL",
        "ex_calf_raises": "Calf Raises",
        "ex_glute_bridges": "Glute Bridges",
        "ex_hip_thrusts": "Hip Thrusts",
        "ex_step_ups": "Step-ups",
        "ex_wall_sit": "Wall Sit",
        "ex_squats": "Squats",
        "ex_jump_squats": "Jump Squats",
        "ex_plank": "Plank",
        "ex_side_plank": "Side Plank",
        "ex_mountain_climbers": "Mountain Climbers",
        "ex_leg_raises": "Leg Raises",
        "ex_russian_twists": "Russian Twists",
        "ex_crunches": "Crunches",
        "ex_bicycle_crunches": "Bicycle Crunches",
        "ex_dead_bug": "Dead Bug",
        "ex_superman": "Superman",
        "ex_burpees": "Burpees",
        "ex_jumping_jacks": "Jumping Jacks",
        "ex_high_knees": "High Knees",

        // Workout Types
        "workout_full_body": "Full Body",
        "workout_upper_body": "Upper Body",
        "workout_lower_body": "Lower Body",
        "workout_push": "Push",
        "workout_pull": "Pull",
        "workout_legs": "Legs",
        "workout_arms": "Arms",
        "workout_core": "Core",
        "workout_challenge": "Challenge",

        // New Exercises
        "ex_arnold_press": "Arnold Press",
        "ex_incline_curls": "Incline Curls",
        "ex_skull_crushers": "Skull Crushers",
        "ex_sumo_squats": "Sumo Squats",
        "ex_weighted_crunches": "Weighted Crunches",
        "ex_archer_push_ups": "Archer Push-ups",
        "ex_handstand_hold": "Handstand Hold",
        "ex_bench_dips": "Bench Dips",
        "ex_pistol_squats": "Pistol Squats",
        "ex_jumping_lunges": "Jumping Lunges",
        "ex_single_leg_glute_bridge": "Single Leg Glute Bridge",
        "ex_donkey_kicks": "Donkey Kicks",
        "ex_hollow_hold": "Hollow Hold",
        "ex_v_ups": "V-ups",
        "ex_reverse_snow_angels": "Reverse Snow Angels",
        "ex_star_jumps": "Star Jumps",
        "ex_dumbbell_complex": "Dumbbell Complex",
        "ex_complex_note": "Curl + Press + Squat chained",

        // Meal Names
        "meal_oatmeal_banana": "Oatmeal with Banana",
        "meal_eggs_toast": "Eggs and Toast",
        "meal_protein_smoothie": "Protein Smoothie",
        "meal_greek_yogurt": "Greek Yogurt with Fruits",
        "meal_chicken_rice": "Chicken Rice Vegetables",
        "meal_pasta_beef": "Pasta Ground Beef",
        "meal_salmon_quinoa": "Salmon Quinoa",
        "meal_tuna_salad": "Tuna Salad",
        "meal_steak_potatoes": "Steak and Potatoes",
        "meal_turkey_wrap": "Turkey Wrap",
        "meal_fish_vegetables": "Fish and Vegetables",
        "meal_beef_stir_fry": "Beef Stir Fry",
        "meal_nuts_fruit": "Nuts and Fruits",
        "meal_protein_bar": "Protein Bar",
        "meal_cottage_cheese": "Cottage Cheese",

        // Days
        "day_monday": "Monday",
        "day_tuesday": "Tuesday",
        "day_wednesday": "Wednesday",
        "day_thursday": "Thursday",
        "day_friday": "Friday",
        "day_saturday": "Saturday",
        "day_sunday": "Sunday",

        // Errors
        "error_generation": "Error during generation",
        "error_save": "Error while saving",
        "error_load": "Error while loading",

        // Authentication
        "auth_title": "Create Account",
        "auth_subtitle": "Save your data and sync across devices",
        "auth_skip": "Continue without account",
        "auth_signup": "Sign Up",
        "auth_signin": "Sign In",
        "auth_email": "Email",
        "auth_password": "Password",
        "auth_google": "Continue with Google",
        "auth_or": "or",
        "auth_sign_out": "Sign Out",
        "auth_sign_out_confirm": "Do you really want to sign out? You will need to sign in again to access your data.",
        "auth_delete_account": "Delete Account",
        "auth_delete_confirm": "Are you sure you want to delete your account? All your data will be lost.",
        "auth_anonymous": "Guest Account",
        "auth_logged_in_as": "Logged in",
        "auth_not_logged_in": "Not logged in",
        "settings_account": "Account",
        "settings_appearance": "Appearance",
        "settings_theme": "Theme",
        "settings_accent_color": "Accent color",
        "settings_danger_zone": "Danger zone",

        // Theme modes
        "theme_mode_system": "System",
        "theme_mode_light": "Light",
        "theme_mode_dark": "Dark",

        // Accent colors
        "accent_color_teal": "Teal",
        "accent_color_coral": "Coral",
        "accent_color_purple": "Purple",
        "accent_color_blue": "Blue",
        "accent_color_green": "Green",
        "accent_color_orange": "Orange",
        "accent_color_pink": "Pink",

        // Notifications
        "settings_workout_time": "Workout time",
        "notification_workout_time": "Time for your workout! 💪",
        "notification_new_week": "Plan your week! Generate your workout program for the upcoming week 📅",
        "notification_weekly_summary": "Your week is done! Check your recap and plan the next one 📊",

        // Weekly Summary
        "summary_title": "Weekly Recap",
        "summary_completed": "completed",
        "summary_sessions": "Sessions",
        "summary_training_time": "Total time",
        "summary_streak": "Streak",
        "summary_days": "days",
        "summary_avg_rating": "Avg rating",
        "summary_weight_progress": "Weight progress",
        "summary_start": "Start",
        "summary_end": "End",
        "summary_best_exercises": "Best improvements",
        "summary_nutrition": "Average nutrition",
        "summary_recommendations": "AI Recommendations",
        "summary_no_recommendations": "Complete a few sessions to get personalized recommendations.",
        "summary_generate_next_week": "Generate next week",
        "summary_banner_title": "Weekly recap available",
        "summary_banner_subtitle": "View your progress and plan next week",

        // Loading Overlays
        "meals_generating_title": "Preparing your meals",
        "meals_generating_subtitle": "AI is creating a personalized menu for your goals",
        "workouts_generating_title": "Creating your program",
        "workouts_generating_subtitle": "AI is optimizing your workouts for the week",

        // Premium / Subscription
        "premium_title": "FitAI Premium",
        "premium_unlock": "Unlock the full power of AI",
        "premium_subtitle": "Unlimited personalized programs and meal plans",
        "premium_feature_ai": "Unlimited AI",
        "premium_feature_ai_desc": "Generate programs and meals without limits",
        "premium_feature_meals": "Personalized Meals",
        "premium_feature_meals_desc": "Daily menus tailored to your goals",
        "premium_feature_workouts": "Adaptive Programs",
        "premium_feature_workouts_desc": "Workouts that evolve with you",
        "premium_feature_summary": "Weekly AI Summary",
        "premium_feature_summary_desc": "Personalized recommendations every week",
        "premium_feature_regenerate": "Unlimited Regeneration",
        "premium_feature_regenerate_desc": "Change your program anytime",
        "premium_monthly": "Monthly",
        "premium_monthly_desc": "Billed monthly, cancel anytime",
        "premium_yearly": "Yearly",
        "premium_yearly_desc": "Best value, save over 30%",
        "premium_month": "month",
        "premium_subscribe": "Subscribe",
        "premium_restore": "Restore purchases",
        "premium_legal": "Subscription auto-renews. Cancel anytime in App Store settings.",
        "premium_terms": "Terms of Use",
        "premium_privacy": "Privacy Policy",
        "premium_loading_error": "Unable to load subscriptions",
        "premium_retry": "Retry",
        "premium_remaining": "generations left this month",
        "premium_limit_reached": "Limit reached this month",
        "premium_upgrade": "Go Premium",
        "premium_badge": "Premium",
        "premium_free_trial": "7 days free",
        "settings_subscription": "Subscription",
        "settings_subscription_status": "Status",
        "settings_subscription_free": "Free",
        "settings_subscription_premium": "Premium",
        "settings_manage_subscription": "Manage subscription",
        "settings_premium_active": "Subscription active",
        "settings_free_plan": "Free Plan",
        "settings_free_limits": "Limited AI generations",
        "settings_workouts_remaining": "Programs remaining",
        "settings_meals_remaining": "Menus remaining",
    ]
}

// MARK: - String Extension for Localization

extension String {
    @MainActor
    func localized(with manager: LocalizationManager) -> String {
        manager.localized(self)
    }
}

// MARK: - Environment Key

struct LocalizationKey: EnvironmentKey {
    @MainActor static let defaultValue = LocalizationManager.shared
}

extension EnvironmentValues {
    var localization: LocalizationManager {
        get { self[LocalizationKey.self] }
        set { self[LocalizationKey.self] = newValue }
    }
}

